<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\TonnUr.Application\TonnUr.Application.csproj" />
      <ProjectReference Include="..\TonnUr.Domain\TonnUr.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.5" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.5">
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        <PrivateAssets>all</PrivateAssets>
      </PackageReference>
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.1" />
    </ItemGroup>

    <ItemGroup>
      <Reference Include="Microsoft.Extensions.Configuration.Abstractions">
        <HintPath>..\..\..\..\.dotnet\packs\Microsoft.AspNetCore.App.Ref\10.0.5\ref\net10.0\Microsoft.Extensions.Configuration.Abstractions.dll</HintPath>
      </Reference>
    </ItemGroup>

</Project>
