<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="NetArchTest.Rules" Version="1.3.2" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="../../src/TonnUr.Domain/TonnUr.Domain.csproj" />
        <ProjectReference Include="../../src/TonnUr.Application/TonnUr.Application.csproj" />
        <ProjectReference Include="../../src/TonnUr.Infrastructure/TonnUr.Infrastructure.csproj" />
        <ProjectReference Include="../../src/TonnUr.Api/TonnUr.Api.csproj" />
    </ItemGroup>
</Project>