<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="NSubstitute" Version="5.3.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="../../src/TonnUr.Domain/TonnUr.Domain.csproj" />
        <ProjectReference Include="../../src/TonnUr.Application/TonnUr.Application.csproj" />
    </ItemGroup>
</Project>
