<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="NSubstitute" Version="5.3.0" />
        <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="10.0.0" />
        <PackageReference Include="Testcontainers.PostgreSql" Version="3.10.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="../../src/TonnUr.Domain/TonnUr.Domain.csproj" />
        <ProjectReference Include="../../src/TonnUr.Application/TonnUr.Application.csproj" />
        <ProjectReference Include="../../src/TonnUr.Infrastructure/TonnUr.Infrastructure.csproj" />
        <ProjectReference Include="../../src/TonnUr.Api/TonnUr.Api.csproj" />
    </ItemGroup>
</Project>